name: C/C++ CI

on:
  push:
    branches: [ master, ci, V_8_7_P1_parallel ]
  pull_request:
    branches: [ master, V_8_7_P1_parallel ]

jobs:
  ci:
    if: github.repository != 'openssh/openssh-portable-selfhosted'
    strategy:
      fail-fast: false
      matrix:
        # First we test all OSes in the default configuration.
        os: [ubuntu-20.04]
        configs: [default]
        # Then we include any extra configs we want to test for specific VMs.
        # Valgrind slows things down quite a bit, so start them first.
        include:
          - { os: ubuntu-20.04, configs: valgrind-1 }
          - { os: ubuntu-20.04, configs: valgrind-2 }
          - { os: ubuntu-20.04, configs: valgrind-3 }
          - { os: ubuntu-20.04, configs: valgrind-4 }
          - { os: ubuntu-20.04, configs: valgrind-unit }
          - { os: ubuntu-20.04, configs: c89 }
          - { os: ubuntu-20.04, configs: pam }
          - { os: ubuntu-20.04, configs: kitchensink }
          - { os: ubuntu-20.04, configs: libressl-2.2.9 }
          - { os: ubuntu-20.04, configs: libressl-2.8.3 }
          - { os: ubuntu-20.04, configs: libressl-3.0.2 }
          - { os: ubuntu-20.04, configs: libressl-3.2.5 }
          - { os: ubuntu-20.04, configs: openssl-noec }
          - { os: ubuntu-20.04, configs: openssl-1.0.1 }
          - { os: ubuntu-20.04, configs: openssl-1.0.1u }
          - { os: ubuntu-20.04, configs: openssl-1.0.2u }
          - { os: ubuntu-20.04, configs: openssl-1.1.0h }
          - { os: ubuntu-20.04, configs: openssl-1.1.1 }
          - { os: ubuntu-20.04, configs: openssl-1.1.1k }
          - { os: ubuntu-20.04, configs: kerberos5 }
          - { os: ubuntu-20.04, configs: libedit }
          - { os: ubuntu-20.04, configs: sk }
          - { os: ubuntu-20.04, configs: selinux }
          - { os: ubuntu-20.04, configs: without-openssl }
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: setup CI system
      run: ./.github/setup_ci.sh ${{ matrix.configs }}
    - name: autoreconf
      run: autoreconf
    - name: configure
      run: ./.github/configure.sh ${{ matrix.configs }}
    - name: make
      run: make -j2
    - name: make tests
      run: ./.github/run_test.sh ${{ matrix.configs }}
      env:
        TEST_SSH_UNSAFE_PERMISSIONS: 1
    - name: save logs
      if: failure()
      uses: actions/upload-artifact@main
      with:
        name: ${{ matrix.os }}-${{ matrix.configs }}-logs
        path: |
          config.h
          config.log
          regress/*.log
          regress/valgrind-out/
